services:
  db:
    image: postgres:15.5
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dealdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: nest_backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 7000
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_DB: dealdb
      POSTGRES_PASSWORD: admin123
      POSTGRES_PORT: 5432
      FRONTEND_URL: http://localhost:3001
    ports:
      - "7001:7000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: next_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:7001"
      NEXT_PUBLIC_BACKEND_URL_INTERNAL: "http://backend:7000"
    ports:
      - "3001:3000"

volumes:
  postgres_data: